<?php

namespace DashboardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlimentRepository extends EntityRepository
{

    public function addAll()
    {
        $qb = $this->createQueryBuilder('a');

        $query = $qb;

        $result = $query->getQuery()->execute();

        return $result;
    }

}
